# Generated by Django 5.0.1 on 2024-01-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(default='', max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('prodi', models.CharField(choices=[('Teknik Informatika', 'Teknik Informatika'), ('Sistem Informasi', 'Sistem Informasi'), ('Manajemen', 'Manajemen'), ('Akuntansi', 'Akuntansi')], default='Teknik Informatika', max_length=50)),
                ('kelas', models.CharField(max_length=20)),
                ('alamat', models.TextField(max_length=255)),
            ],
        ),
    ]
